### ISSUE TITLE
Feedback Angers.io V2

### ISSUE THREAD

**Issue by remilanoes** [mainelabs/techlist#73]
feedback angers.io v2

**Comment by remilanoes** [comment]
Label Contacter -> Contacter sur fiche entreprise

**Comment by remilanoes** [comment]
Rendre plus visible la barre de recherche. Idées: arrière plan du champ en changeant l'opacité pour distinguer de l'arrière plan principal

**Comment by scharrier** [comment]
> Label Contacter -> Contacter sur fiche entreprise

Après réflexion, je pense que l'infinitif est plus adapté, ici. A re-discuter si nécessaire, mais je pense que le vouvoiement n'est utile que dans certaines circonstance (le call to action, par exemple).

> Rendre plus visible la barre de recherche. Idées: arrière plan du champ en changeant l'opacité pour distinguer de l'arrière plan principal

Fait dans https://github.com/mainelabs/techlist/pull/75.
